### ISSUE TITLE
Equinix Metal Provisiner Errors

### ISSUE THREAD

**Issue by dirien** [inlets/cloud-provision#12]
Hi,

i get following errors, when using the Equinix Metal Provisioner:

1. Default Region am1 does not exist
```bash
Using provider: equinix-metal
Requesting host: reverent-khayyam0 in ams1, from equinix-metal
2021/07/27 06:31:29 [DEBUG] POST https://api.equinix.com/metal/v1/projects/xx/devices
POST https://api.equinix.com/metal/v1/projects/xxx/devices: 422 ams1 is not a valid facility 
```

2. You can not create an Equinix Metal Server without an SSH Key anymore:

```bash
Using provider: equinix-metal
Requesting host: magical-johnson8 in fr2, from equinix-metal
2021/07/27 06:36:30 [DEBUG] POST https://api.equinix.com/metal/v1/projects/xxx/devices
POST https://api.equinix.com/metal/v1/projects/xxx/devices: 422 must have at least one SSH key or explicitly send no_ssh_keys option 
```
See -> https://feedback.equinixmetal.com/platform/p/allow-to-deploy-servers-without-ssh-key
And new API for the no_ssh_keys option -> https://metal.equinix.com/developers/api/devices/#devices-createdevice

For issue 2 we need to update the Go lib -> 0.17.0

**Comment by alexellis** [comment]
Thanks for the PR, I've just merged it and cut a release tag for you: https://github.com/inlets/cloud-provision/releases/tag/v0.5.1

cc @rawkode
