### ISSUE TITLE
Scaleway STARDUST1-S Instance Type Support

### ISSUE THREAD

**Issue by emolitor** [inlets/cloud-provision#9]
Scaleway now has a STARDUST1-S Instance Type "STARDUST1-S" 
1 vCPU, 1 GB of RAM, 1 IPv4 address, 10GB storage, up-to 100Mbps Bandwidth. €0.0025/hour.

Having support for this would be by far the lowest cost option to use with inlets for European customers. It would be nice to add support for Amsterdam regions as well.

**Comment by alexellis** [comment]
Thank you for the suggestion. We will take a look.

Pinging @jsiebens 

Also, check out Fly.io where you can run three tunnels for free: https://inlets.dev/blog/2021/07/07/inlets-fly-tutorial.html

**Comment by dirien** [comment]
I love the stardust instances. The ony thing could be the reliability on the availability:

> Every month, limited numbers of Stardust Instances will be released

> Stardust stocks will be limited at launch: one Stardust in PAR1, one in AMS1…if you are quick enough to get one!
>More instances will be added to the pool regularly. These exclusive releases are called Stardust rain, and you don’t want to miss them. Here’s how it works.

I am not sure how to work with this Stardust rain events in inlets. One idea could be a cascading provisioning. First try to provision a stardust in the prefered region. Iterate to the next region or fallback to the developer instance.

Or adding a stardust flag (--promo-instance :D)...

**Comment by alexellis** [comment]
It sounds like if you can get one of these instances then you are very lucky to have it and are allowed only one.

For that reason it may not make a good fit in our automation tools.

But don't let that stop you installing inlets PRO onto any VM you been provision.

Let us know if Scaleway changes their policy and we can reconsider.

**Comment by jsiebens** [comment]
This library already supports using a certain plan and/or region, so no changes are required here.

Both tools using this library ([inletsctl](https://github.com/inlets/inletsctl) and [inlets-operator](https://github.com/inlets/inlets-operator)) have already a flag to select a region, perhaps we good add a flag to select the plan as well.

**Comment by alexellis** [comment]
The flag is available but only set if on Equinix Metal. Happy for someone to update inletsctl to accept the plan flag for the other provisioners. Should be an easy PR for someone to make

**Comment by emolitor** [comment]
Depending on how busy my weekend is I might take a stab at this.

- Eric

**Comment by jsiebens** [comment]
I had a little bit of time this evening: https://github.com/inlets/inletsctl/pull/106

**Comment by dirien** [comment]
noice! ❤️

**Comment by alexellis** [comment]
Looks like we may have got there sooner than expected @emolitor, but it'd be great if you can test it on your setup.

I've cut a new release binary

**Comment by emolitor** [comment]
Thanks, will be able to test tomorrow.

**Comment by emolitor** [comment]
Works for me, many thanks everyone!

**Comment by dirien** [comment]
For everyone stumbling over this: Keep in mind to check, in which region a stardust instance is available and set --region too!

```bash
inletsctl create --provider scaleway ... --plan=STARDUST1-S --region=ams1|par1
```
